### ISSUE TITLE
Single email thread per ticket

### ISSUE THREAD

**Issue by scottgonzalez** [scottgonzalez/debt#14]
It'd be nice to have just a single email thread per ticket, even if the title of the ticket changes.

Not sure how to handle this.

**Comment by jzaefferer** [comment]
For starters, don't prepend `Re:` to the subject for any emails after the initial notification.

**Comment by jzaefferer** [comment]
Also, duplicate of #10?

**Comment by scottgonzalez** [comment]
Yup. I moved our comments over there.
