### ISSUE TITLE
Use markdown for tickets

### ISSUE THREAD

**Issue by scottgonzalez** [scottgonzalez/debt#16]
description and comments

**Comment by jzaefferer** [comment]
Preferably with the same flavor as GitHub.

**Comment by jzaefferer** [comment]
What about supporting at-mentions in comments and tickets? On GitHub issues, mentioning someone also causes a subscription to the ticket.

**Comment by scottgonzalez** [comment]
That sounds good. I've created a separate ticket for that (#21) since it will involve more than just using the `marked` module.
