### ISSUE TITLE
Ditch CLA, use DCO instead

### ISSUE THREAD

**Issue by scottgonzalez** [scottgonzalez/debt#28]
- [x] Create DCO
- [x] Create Contributing Guidlines which link to DCO
- [x] Change CLA verification to DCO verification

**Comment by mgol** [comment]
What's a DCO?

**Comment by scottgonzalez** [comment]
A Developer's Certificate of Origin. The DEBT DCO will be very similar to the [phpMyAdmin DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). For a more complex DCO, you can view the [Linux kernel DCO](https://github.com/torvalds/linux/blob/319e2e3f63c348a9b66db4667efa73178e18b17d/Documentation/SubmittingPatches#L307).
